export interface Product {
  id: string;
  name: string;
  category: string;
  subcategory?: string;
  image: string;
  images?: string[];
  description: string;
  specs: Record<string, string>;
}

export interface NewsItem {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  image: string;
}

export interface TimelineItem {
  year: string;
  title: string;
  description: string;
}

export const productCategories = [
  'cpu-cooler', 'server-cooler', 'pc-case', 'power-supply', 'laptop-cooling', 'accessories'
] as const;

export const productSubcategories: Record<string, string[]> = {
  'cpu-cooler': ['air-cooler', 'aio-water-cooler', 'pc-case-fan'],
  'server-cooler': ['air-server-cooler', 'water-server-cooler'],
};

export const categoryIcons: Record<string, string> = {
  'cpu-cooler': 'Cpu',
  'server-cooler': 'Server',
  'pc-case': 'Box',
  'power-supply': 'Zap',
  'laptop-cooling': 'Laptop',
  'accessories': 'Cable',
};

export const products: Product[] = [
  // ===== CPU COOLER > AIR COOLER =====
  {
    id: 'cool-air-01',
    name: 'SQH TowerAir X7',
    category: 'cpu-cooler',
    subcategory: 'air-cooler',
    image: 'https://placehold.co/400x300/0a0e27/00d4ff?text=Air+Cooler+X7',
    description: 'Dual-Tower Air CPU Cooler with 7 Heat Pipes',
    specs: {
      'Type': 'Dual-Tower Air Cooler',
      'Heat Pipes': '7x 6mm Copper',
      'Fan': '2x 120mm PWM',
      'Fan Speed': '500–1800 RPM',
      'Noise': '≤ 28 dB(A)',
      'TDP': '200W',
      'Height': '158mm',
      'Socket': 'Intel LGA 1700/1851 / AMD AM4/AM5',
    },
  },
  {
    id: 'cool-air-02',
    name: 'SQH FrostBlade 140',
    category: 'cpu-cooler',
    subcategory: 'air-cooler',
    image: 'https://placehold.co/400x300/0a0e27/00d4ff?text=Air+Cooler+140',
    description: 'Single-Tower Slim Air Cooler for Compact Builds',
    specs: {
      'Type': 'Single-Tower Air Cooler',
      'Heat Pipes': '4x 6mm Copper',
      'Fan': '1x 140mm PWM',
      'Fan Speed': '600–1600 RPM',
      'Noise': '≤ 25 dB(A)',
      'TDP': '150W',
      'Height': '155mm',
      'Socket': 'Intel LGA 1700/1851 / AMD AM4/AM5',
    },
  },
  // ===== CPU COOLER > AIO WATER COOLER =====
  {
    id: 'sqha01-120',
    name: 'SQH-A01-120B AIO Water Cooler 120mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA01-120_main.png',
    description: '120mm AIO Liquid Cooler, Minimalist Round Cold Head, PWM Fan & PWM Pump',
    images: [
      '/images/products/SQHA01-120_main.png',
      '/images/products/SQHA01-120_2.png',
      '/images/products/SQHA01-120_3.png',
      '/images/products/SQHA01-120_4.png',
    ],
    specs: {
      'Fan Size': '120mm',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '150W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '154×120×27 mm',
      'Pump Head': '72×72×54 mm',
      'Tube Length': '320 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'Fixed RGB',
      'Fan Connector': '2510-3Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '3.7W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '5W',
      'Airflow': '62 CFM (max)',
      'Air Pressure': '1.5 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha01-240',
    name: 'SQH-A01-240B AIO Water Cooler 240mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA01-240_main.png',
    description: '240mm AIO Liquid Cooler, Minimalist Round Cold Head, ARGB PWM Fan & Pump',
    images: [
      '/images/products/SQHA01-240_main.png',
      '/images/products/SQHA01-240_2.png',
      '/images/products/SQHA01-240_3.png',
      '/images/products/SQHA01-240_4.png',
    ],
    specs: {
      'Fan Size': '240mm (2x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '250W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '276×120×27 mm',
      'Pump Head': '72×72×60 mm',
      'Tube Length': '390 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha01-360',
    name: 'SQH-A01-360B AIO Water Cooler 360mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA01-360_main.png',
    description: '360mm AIO Liquid Cooler, Minimalist Round Cold Head, ARGB PWM Fan & Pump',
    images: [
      '/images/products/SQHA01-360_main.png',
      '/images/products/SQHA01-360_2.png',
      '/images/products/SQHA01-360_3.png',
      '/images/products/SQHA01-360_4.png',
    ],
    specs: {
      'Fan Size': '360mm (3x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '300W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '396×120×27 mm',
      'Pump Head': '72×72×60 mm',
      'Tube Length': '390 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha02-240',
    name: 'SQH-A02-240B AIO Water Cooler 240mm LCD',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA02-240_main.png',
    description: '240mm AIO with 3.95" IPS LCD Screen, ARGB PWM Silent Fans, DIY Video Upload',
    images: [
      '/images/products/SQHA02-240_main.png',
      '/images/products/SQHA02-240_2.png',
      '/images/products/SQHA02-240_3.png',
      '/images/products/SQHA02-240_4.png',
    ],
    specs: {
      'Fan Size': '240mm (2x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '250W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '276×120×27 mm',
      'Pump Head': '83×83×69 mm',
      'Tube Length': '390 mm',
      'Screen Size': '3.95 inches',
      'Screen Type': 'IPS',
      'Screen Resolution': '480×480',
      'Screen Interface': 'USB 2.0 (9-pin)',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha02-360',
    name: 'SQH-A02-360B AIO Water Cooler 360mm LCD',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA02-360_main.png',
    description: '360mm AIO with 3.95" IPS LCD Screen, ARGB PWM Silent Fans, DIY Video Upload — Flagship Model',
    images: [
      '/images/products/SQHA02-360_main.png',
      '/images/products/SQHA02-360_2.png',
      '/images/products/SQHA02-360_3.png',
      '/images/products/SQHA02-360_4.png',
    ],
    specs: {
      'Fan Size': '360mm (3x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '300W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '396×120×27 mm',
      'Pump Head': '83×83×69 mm',
      'Tube Length': '390 mm',
      'Screen Size': '3.95 inches',
      'Screen Type': 'IPS',
      'Screen Resolution': '480×480',
      'Screen Interface': 'USB 2.0 (9-pin)',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  // ===== NEW: SQHA03 Series =====
  {
    id: 'sqha03-120',
    name: 'SQH-A03-120B AIO Water Cooler 120mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA03-120_main.png',
    description: '120mm AIO Liquid Cooler, ARGB PWM Silent Fans, Multi-Platform Compatible',
    images: [
      '/images/products/SQHA03-120_main.png',
      '/images/products/SQHA03-120_2.png',
      '/images/products/SQHA03-120_3.png',
      '/images/products/SQHA03-120_4.png',
    ],
    specs: {
      'Fan Size': '120mm',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '150W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '154×120×27 mm',
      'Pump Head': '72×72×54 mm',
      'Tube Length': '320 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '3.7W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '5W',
      'Airflow': '62 CFM (max)',
      'Air Pressure': '1.5 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha03-240',
    name: 'SQH-A03-240B AIO Water Cooler 240mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA03-240_main.png',
    description: '240mm AIO Liquid Cooler, ARGB PWM Silent Fans, Multi-Platform Compatible',
    images: [
      '/images/products/SQHA03-240_main.png',
      '/images/products/SQHA03-240_2.png',
      '/images/products/SQHA03-240_3.png',
      '/images/products/SQHA03-240_4.png',
    ],
    specs: {
      'Fan Size': '240mm (2x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '250W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '276×120×27 mm',
      'Pump Head': '72×72×60 mm',
      'Tube Length': '390 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha03-360',
    name: 'SQH-A03-360B AIO Water Cooler 360mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA03-360_main.png',
    description: '360mm AIO Liquid Cooler, ARGB PWM Silent Fans, Multi-Platform Compatible',
    images: [
      '/images/products/SQHA03-360_main.png',
      '/images/products/SQHA03-360_2.png',
      '/images/products/SQHA03-360_3.png',
      '/images/products/SQHA03-360_4.png',
    ],
    specs: {
      'Fan Size': '360mm (3x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '300W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '396×120×27 mm',
      'Pump Head': '72×72×60 mm',
      'Tube Length': '390 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  // ===== NEW: SQHA04 Series =====
  {
    id: 'sqha04-120',
    name: 'SQH-A04-120B AIO Water Cooler 120mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA04-120_main.png',
    description: '120mm AIO Liquid Cooler, ARGB PWM Silent Fans, Premium Build Quality',
    images: [
      '/images/products/SQHA04-120_main.png',
      '/images/products/SQHA04-120_2.png',
      '/images/products/SQHA04-120_3.png',
      '/images/products/SQHA04-120_4.png',
    ],
    specs: {
      'Fan Size': '120mm',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '150W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '154×120×27 mm',
      'Pump Head': '72×72×54 mm',
      'Tube Length': '320 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '3.7W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '5W',
      'Airflow': '62 CFM (max)',
      'Air Pressure': '1.5 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha04-240',
    name: 'SQH-A04-240B AIO Water Cooler 240mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA04-240_main.png',
    description: '240mm AIO Liquid Cooler, ARGB PWM Silent Fans, Premium Build Quality',
    images: [
      '/images/products/SQHA04-240_main.png',
      '/images/products/SQHA04-240_2.png',
      '/images/products/SQHA04-240_3.png',
      '/images/products/SQHA04-240_4.png',
    ],
    specs: {
      'Fan Size': '240mm (2x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '250W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '276×120×27 mm',
      'Pump Head': '72×72×60 mm',
      'Tube Length': '390 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha04-360',
    name: 'SQH-A04-360B AIO Water Cooler 360mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA04-360_main.png',
    description: '360mm AIO Liquid Cooler, ARGB PWM Silent Fans, Premium Build Quality',
    images: [
      '/images/products/SQHA04-360_main.png',
      '/images/products/SQHA04-360_2.png',
      '/images/products/SQHA04-360_3.png',
      '/images/products/SQHA04-360_4.png',
    ],
    specs: {
      'Fan Size': '360mm (3x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '300W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '396×120×27 mm',
      'Pump Head': '72×72×60 mm',
      'Tube Length': '390 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'Fan Connector': '2510-4Pin',
      'Pump Connector': '2510-4Pin',
      'Fan Voltage': 'DC 12V',
      'Fan Power': '2.6W (max)',
      'Pump Voltage': 'DC 12V/5V',
      'Pump Power': '4.5W',
      'Airflow': '65 CFM (max)',
      'Air Pressure': '1.6 mmH2O (max)',
      'Fan Bearing': 'Hydraulic',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  // ===== NEW: SQHA05/06/07 Series (images pending) =====
  {
    id: 'sqha05-120',
    name: 'SQH-A05-120B AIO Water Cooler 120mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA05-120_main.png',
    images: ['/images/products/SQHA05-120_main.png', '/images/products/SQHA05-120_2.png', '/images/products/SQHA05-120_3.png', '/images/products/SQHA05-120_4.png'],
    description: '120mm AIO Liquid Cooler, ARGB PWM Silent Fan',
    specs: {
      'Fan Size': '120mm',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '150W',
      'Noise Level': '≤ 28 dB(A)',
      'Radiator Size': '154×120×27 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha05-240',
    name: 'SQH-A05-240B AIO Water Cooler 240mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA05-240_main.png',
    images: ['/images/products/SQHA05-240_main.png', '/images/products/SQHA05-240_2.png', '/images/products/SQHA05-240_3.png', '/images/products/SQHA05-240_4.png'],
    description: '240mm AIO Liquid Cooler, ARGB PWM Silent Fans',
    specs: {
      'Fan Size': '240mm (2x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '250W',
      'Noise Level': '≤ 26 dB(A)',
      'Radiator Size': '277×120×27 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha05-360',
    name: 'SQH-A05-360B AIO Water Cooler 360mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: '/images/products/SQHA05-360_main.png',
    images: ['/images/products/SQHA05-360_main.png', '/images/products/SQHA05-360_2.png', '/images/products/SQHA05-360_3.png', '/images/products/SQHA05-360_4.png'],
    description: '360mm AIO Liquid Cooler, ARGB PWM Silent Fans',
    specs: {
      'Fan Size': '360mm (3x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '300W',
      'Noise Level': '≤ 23 dB(A)',
      'Radiator Size': '396×120×27 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha06-360',
    name: 'SQH-A06-360B AIO Water Cooler 360mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: 'https://placehold.co/400x300/0a0e27/00d4ff?text=SQHA06-360',
    description: '360mm AIO Liquid Cooler, Advanced Cooling Performance, ARGB PWM Fans',
    specs: {
      'Fan Size': '360mm (3x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '300W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '396×120×27 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  {
    id: 'sqha07-360',
    name: 'SQH-A07-360B AIO Water Cooler 360mm',
    category: 'cpu-cooler',
    subcategory: 'aio-water-cooler',
    image: 'https://placehold.co/400x300/0a0e27/00d4ff?text=SQHA07-360',
    description: '360mm AIO Liquid Cooler, Ultimate Cooling Solution, ARGB PWM Fans',
    specs: {
      'Fan Size': '360mm (3x 120mm)',
      'Fan Speed': '800–1800 RPM',
      'Pump Speed': '2400–3100 ±10% RPM',
      'TDP': '300W',
      'Noise Level': '23 dB (Max.)',
      'Radiator Size': '396×120×27 mm',
      'Socket (Intel)': 'LGA 115X / 1700 / 1851 / 1366',
      'Socket (AMD)': 'AM3 / AM4 / AM5',
      'LED Lighting': 'ARGB (motherboard connectors)',
      'MOQ': '500 pcs',
      'Certifications': 'CE, FCC, RoHS',
    },
  },
  // ===== CPU COOLER > PC CASE FAN =====
  {
    id: 'fan-01',
    name: 'SQH AeroFlow 120 ARGB',
    category: 'cpu-cooler',
    subcategory: 'pc-case-fan',
    image: 'https://placehold.co/400x300/0a0e27/00d4ff?text=Case+Fan+120',
    description: '120mm ARGB PWM Case Fan (3-Pack)',
    specs: {
      'Size': '120×120×25mm',
      'Speed': '500–1800 RPM',
      'Airflow': '62.5 CFM',
      'Noise': '≤ 26 dB(A)',
      'Bearing': 'Fluid Dynamic Bearing',
      'RGB': 'ARGB (5V 3-Pin)',
      'Connector': 'PWM 4-Pin + ARGB',
      'Package': '3-Pack',
    },
  },
  // ===== PC CASE =====
  {
    id: 'case-01',
    name: 'SQH HyperView 7000X',
    category: 'pc-case',
    image: 'https://placehold.co/400x300/0a0e27/6c5ce7?text=Case+7000X',
    description: 'Full-Tower Tempered Glass RGB Case',
    specs: {
      'Type': 'Full Tower',
      'Motherboard': 'E-ATX / ATX / mATX / ITX',
      'GPU Clearance': 'Up to 450mm',
      'CPU Cooler': 'Up to 190mm',
      'Fan Support': 'Up to 10x 120mm',
      'Radiator': 'Up to 420mm (front)',
      'Material': 'SPCC Steel + Tempered Glass',
    },
  },
  {
    id: 'case-02',
    name: 'SQH MiniView mATX',
    category: 'pc-case',
    image: 'https://placehold.co/400x300/0a0e27/6c5ce7?text=Mini+Case',
    description: 'Compact mATX Case with Mesh Front Panel',
    specs: {
      'Type': 'Mid Tower (mATX)',
      'Motherboard': 'mATX / ITX',
      'GPU Clearance': 'Up to 330mm',
      'CPU Cooler': 'Up to 165mm',
      'Fan Support': 'Up to 6x 120mm',
      'Radiator': 'Up to 240mm (front)',
      'Material': 'SPCC Steel + Mesh',
    },
  },
  // ===== POWER SUPPLY =====
  {
    id: 'psu-01',
    name: 'SQH Thor 1200W Platinum',
    category: 'power-supply',
    image: 'https://placehold.co/400x300/0a0e27/00d4ff?text=PSU+1200W',
    description: '1200W 80+ Platinum Fully Modular',
    specs: {
      'Wattage': '1200W',
      'Efficiency': '80+ Platinum',
      'Modular': 'Fully Modular',
      'Fan': '135mm FDB (Zero RPM Mode)',
      'Protection': 'OVP/UVP/SCP/OTP/OPP',
      'ATX': '3.0 / PCIe 5.0 Ready',
      'Warranty': '12 Years',
    },
  },
  {
    id: 'psu-02',
    name: 'SQH Storm 850W Gold',
    category: 'power-supply',
    image: 'https://placehold.co/400x300/0a0e27/00d4ff?text=PSU+850W',
    description: '850W 80+ Gold Semi-Modular PSU',
    specs: {
      'Wattage': '850W',
      'Efficiency': '80+ Gold',
      'Modular': 'Semi-Modular',
      'Fan': '120mm HDB (Smart Fan)',
      'Protection': 'OVP/UVP/SCP/OTP/OPP/OCP',
      'ATX': '3.0 / PCIe 5.0 Ready',
      'Warranty': '7 Years',
    },
  },
  // ===== LAPTOP COOLING =====
  {
    id: 'laptop-01',
    name: 'SQH ChillPad Pro 17',
    category: 'laptop-cooling',
    image: 'https://placehold.co/400x300/0a0e27/6c5ce7?text=Laptop+Cooler',
    description: '17" Laptop Cooling Pad with 6 Fans',
    specs: {
      'Size': '17-inch Compatible',
      'Fans': '6x 70mm Blue LED',
      'Fan Speed': '1000±10% RPM',
      'Noise': '≤ 21 dB(A)',
      'USB Ports': '2x USB 2.0 Passthrough',
      'Height': 'Adjustable (6 Levels)',
      'Material': 'ABS + Metal Mesh',
      'Power': 'USB Powered (5V)',
    },
  },
  // ===== ACCESSORIES =====
  {
    id: 'acc-01',
    name: 'SQH K95 Mechanical Keyboard',
    category: 'accessories',
    image: 'https://placehold.co/400x300/0a0e27/6c5ce7?text=Keyboard+K95',
    description: 'Wireless Mechanical Gaming Keyboard',
    specs: {
      'Switches': 'Cherry MX Speed Silver',
      'Layout': 'Full-size (104 keys)',
      'Connectivity': 'USB-C / 2.4GHz / BT 5.0',
      'Battery': '4000mAh (up to 300hrs)',
      'Polling': '8000Hz (2.4GHz)',
      'Keycaps': 'Double-shot PBT',
      'RGB': 'Per-key ARGB',
    },
  },
  {
    id: 'acc-02',
    name: 'SQH Thermal Compound X1',
    category: 'accessories',
    image: 'https://placehold.co/400x300/0a0e27/6c5ce7?text=Thermal+Paste',
    description: 'High-Performance Thermal Paste (4g)',
    specs: {
      'Thermal Conductivity': '14.3 W/m·K',
      'Volume': '4g',
      'Specific Gravity': '3.15 g/cm³',
      'Operating Temp': '-50°C to 250°C',
      'Application': 'CPU / GPU / Chipset',
      'Non-conductive': 'Yes (Electrically)',
      'Shelf Life': '8 Years (Unopened)',
    },
  },
];

export const newsItems: NewsItem[] = [
  {
    id: 'n1',
    title: 'SQH Launches Next-Gen DDR5-7200 Memory Series',
    excerpt: 'Our latest DDR5 memory modules achieve breakthrough speeds of 7200MHz with ultra-tight CL34 timings, setting new benchmarks for enthusiast computing.',
    date: '2025-01-15',
    category: 'Product Launch',
    image: 'https://placehold.co/600x400/0a0e27/00d4ff?text=DDR5+Launch',
  },
  {
    id: 'n2',
    title: 'Expanding Global Operations: New Warehouse in Rotterdam',
    excerpt: 'To better serve our European partners, SQH has opened a 15,000 sqm distribution center in Rotterdam, reducing delivery times by 40%.',
    date: '2025-01-08',
    category: 'Company News',
    image: 'https://placehold.co/600x400/0a0e27/6c5ce7?text=Rotterdam+HQ',
  },
  {
    id: 'n3',
    title: 'PCIe Gen5 SSD Technology: What It Means for the Future',
    excerpt: 'An in-depth look at how PCIe Gen5 storage is revolutionizing data transfer speeds and what it means for next-generation computing platforms.',
    date: '2024-12-20',
    category: 'Industry Insights',
    image: 'https://placehold.co/600x400/0a0e27/00d4ff?text=PCIe+Gen5',
  },
  {
    id: 'n4',
    title: 'SQH Wins "Best PC Component Brand 2024" Award',
    excerpt: 'We are honored to receive the Best PC Component Brand award at the annual Global Tech Excellence Awards, recognizing our commitment to quality.',
    date: '2024-12-10',
    category: 'Awards',
    image: 'https://placehold.co/600x400/0a0e27/6c5ce7?text=Award+2024',
  },
  {
    id: 'n5',
    title: 'Sustainability Report: Carbon Neutral Manufacturing by 2026',
    excerpt: 'SQH announces ambitious sustainability goals, including transitioning to 100% renewable energy in all manufacturing facilities by 2026.',
    date: '2024-11-28',
    category: 'Company News',
    image: 'https://placehold.co/600x400/0a0e27/00d4ff?text=Sustainability',
  },
  {
    id: 'n6',
    title: 'The Rise of AI Workloads: How PC Hardware Is Adapting',
    excerpt: 'Exploring how the surge in AI computing demands is driving innovation in GPU architecture, memory bandwidth, and storage solutions.',
    date: '2024-11-15',
    category: 'Industry Insights',
    image: 'https://placehold.co/600x400/0a0e27/6c5ce7?text=AI+Hardware',
  },
];

export const timelineData: TimelineItem[] = [
  { year: '2008', title: 'Founded', description: 'SQH Technology established in Shenzhen, China, starting with memory module manufacturing.' },
  { year: '2011', title: 'First Export', description: 'Began international operations, exporting to Southeast Asian and Middle Eastern markets.' },
  { year: '2014', title: 'Product Line Expansion', description: 'Expanded into SSDs and graphics cards, becoming a full-range PC component manufacturer.' },
  { year: '2016', title: 'Global Reach', description: 'Reached 50+ countries, opened regional offices in Dubai and Los Angeles.' },
  { year: '2019', title: 'R&D Breakthrough', description: 'Established advanced R&D center, filed 200+ patents in thermal management and power delivery.' },
  { year: '2022', title: '100+ Countries', description: 'Surpassed 100 countries served, launched PCIe Gen4 product line.' },
  { year: '2024', title: 'Industry Leader', description: 'Awarded "Best PC Component Brand", launched PCIe Gen5 and DDR5-7200 series.' },
  { year: '2025', title: 'Next Frontier', description: 'Opening European distribution hub, preparing next-gen AI computing hardware solutions.' },
];

export const certifications = [
  { name: 'ISO 9001:2015', desc: 'Quality Management System' },
  { name: 'ISO 14001:2015', desc: 'Environmental Management' },
  { name: 'CE', desc: 'European Conformity' },
  { name: 'FCC', desc: 'Federal Communications Commission' },
  { name: 'RoHS', desc: 'Restriction of Hazardous Substances' },
  { name: 'UL', desc: 'Underwriters Laboratories' },
];
